name: adadocs
channels:
  - conda-forge
dependencies:
  - python==3.8.8
  - ifcopenshell
  - pythonocc-core
  - ipywidgets
  - sphinx
  - nbsphinx
  - jupyter
  - pip
  - pip:
      - sphinx-rtd-theme
